template_chooser:
  display_name: Template
  placeholder: Selecciona un template
  templates:
    - name: nueva-seccion.md
      label: Nueva sección
      description: Para agregar una nueva sección al repositorio
    - name: nueva-empresa.md
      label: Nueva empresa
      description: Para agregar una nueva empresa a la lista
    - name: corregir-empresa.md
      label: Corregir empresa
      description: Para corregir información de una empresa existente
    - name: remover-empresa.md
      label: Remover empresa
      description: Para solicitar la eliminación de una empresa de la lista